# Generated by Django 2.0.3 on 2018-04-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0003_auto_20180405_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
